### ISSUE TITLE
Geolosys Compatibility Issues

### ISSUE THREAD

**Issue by oitsjustjose** [Aang23/UndergroundBiomesConstructs#104]
## Environment
- MinecraftForge 14.23.5.2838
- Geolosys 3.0.0
- UBC 1.3.5
- Windows 10

## Issue

Geolosys compatibility is a bit odd. I've gone through and added the stone blocks from UBC as replacement materials for Geolosys (and they're working), and I thought UBC's Geolosys Compat just wasn't implemented... until now:

![image](https://user-images.githubusercontent.com/3887324/59437532-c2eb9600-8dbf-11e9-9cca-121acebc5fef.png)

So you can see that your awesome compatibility works *outside* of the chunk that the deposit generates in. What can I do on my end to make Geolosys more compatible with UBC's incompatibility?

**Comment by Aang23** [comment]
Not a lot... I'll see what I can do to make sure those are replaced during worldgen. This is due to the way Geolosys generates their ores.
