### ISSUE TITLE
Crash during start up with Plant Mega Pck

### ISSUE THREAD

**Issue by PresquePlayed** [Aang23/UndergroundBiomesConstructs#105]
If I start MC with Plant Mega Pack and Underground biomes (both latest version for 1.12.2) MC crashes with following crashreport:
[crash-2019-06-14_11.43.05-client.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3292223/crash-2019-06-14_11.43.05-client.txt)

**Comment by Aang23** [comment]
Not my fault.
Install Just Enough Ids or equivalent.
