### ISSUE TITLE
Option to disable ores support from each mod

### ISSUE THREAD

**Issue by IronPiston** [Aang23/UndergroundBiomesConstructs#108]
Currently, having multiple mods in a pack that add the same ore leads to both appearing in JEI. Could a config option be added to disable modded ore support on a mod by mod basis?

**Comment by Aang23** [comment]
You mean leaving some ores as is or not generating them at all?

**Comment by IronPiston** [comment]
Not registering them at all, if possible. For example, I have both Thermal Foundation and Geolosys installed, but prefer exclusivly Geolosys ores. I can go into the config and stop all Thermal Foundation ore gen, but I still have to hide a ton of redundent ores from JEI via crafttweaker.

**Comment by Rosethorns** [comment]
a stop gap for this is the empty the json files that Underground biomes generates in its undergroundbiomes>ores folder.

You must have at least 1 generated ore though or underground biomes throws a fit about its creative tab being empty :P
