### ISSUE TITLE
Removal?

### ISSUE THREAD

**Issue by TheRealSmolt** [Aang23/UndergroundBiomesConstructs#109]
This is probably a lot to ask for, but besides starting a new save, is there any way to remove the mod in an existing world that doesn't ruin it?

Something along the lines of replacing all blocks with vanilla ones, but I don't know what with what, or how...

Probably too much to ask for, Thanks.

**Comment by Aang23** [comment]
You could do that using something like this probably : https://github.com/The-Fireplace-Minecraft-Mods/Block-Replacer
But that's not that easy and probably too much work...
