### ISSUE TITLE
Pathway to Sand and Gravel

### ISSUE THREAD

**Issue by sealchan1** [Aang23/UndergroundBiomesConstructs#110]
I am playing survival modded Minecraft 1.12 and I am excited about the new sand and gravel variants of the stones this mod adds.  However, I am not seeing any way to obtain these blocks.  JEI shows no crafting recipes even with "grinders".  The blocks are only shown as substitutes for Vanilla gravel and sand.  World generation does not appear to be using UBC gravels and sands.  Underground I see Vanilla Gravel veins.

Is there currently a way in which I can obtain UBC gravel and sand blocks?

**Comment by sealchan1** [comment]
Okay, I updated my test modpack including UBC (from 1.3.4 to 1.3.5) and moved into new territory in a creative world...it looks like most beaches are now gravel beaches and they are populated with UBC gravels...nice!  And here and there I can also make out some sands along rivers including UBC sands.  Are you, then, still in the process of implementing the world gen aspects of these blocks?

**Comment by sealchan1** [comment]
I also noticed that in a new world it appears that near the spawn site it is Vanilla Sand and Gravel but if you move out from there a few chunks or so it goes to UBC sands and gravel.  Is that coincidence (maybe I spawned in a desert biome) or an expected behavior?

**Comment by Aang23** [comment]
Deserts and beaches aren't enabled by default to prevent strange generation patterns. 
*Sorry for the late answer*
