### ISSUE TITLE
Far from home world gen issue.

### ISSUE THREAD

**Issue by Shannieann** [Aang23/UndergroundBiomesConstructs#112]
Giant chunks of stone spawn randomly sticking out of the ground when using this mod and Far from home.

**Comment by Aang23** [comment]
Could you provide logs, and more infos such as your Forge version, UBC & Far from home versions as well as some screenshots if possible ?

**Comment by Shannieann** [comment]
After I did some more testing it turns out this is more likely a Far from home issue as I took out underground biomes and the giant chunks of stone still generated on a world without it sorry for possibly wasting your time. The previous non UB world I did with it didn't have them so I thought it was UB causing it.
