### ISSUE TITLE
Cannot smelt cobblestone into stone with new blocks

### ISSUE THREAD

**Issue by BliilB** [Aang23/UndergroundBiomesConstructs#117]
First off, thanks for keeping the mod up to date with 1.14.3. I can't seem to smelt any of the cobblestone variants into smooth stone. Also, doesn't seem as though some of the stair and slab variants are in yet. I was also wondering if tools are supposed to be able to be crafted with the cobblestone variants, or if converting them to regular cobblestone is necessary. Thanks again.

**Comment by Aang23** [comment]
Recipes / Tagging (Oredict) is not done yet. That's why you can't craft anything with those & forced to convert them.
Missing blocks (slab & more) will be added later.
That's some of the reasons why it's still **alpha**.

**Comment by Aang23** [comment]
Smelting is fixed now.
