### ISSUE TITLE
Ore Texture Overlays Skipping Non-Opaque Pixels as Block, not as ItemStack

### ISSUE THREAD

**Issue by oitsjustjose** [Aang23/UndergroundBiomesConstructs#119]
I was trying to beautify the overlays a bit, and came across this -- I know that rendering in MC can be a bit wonky, but I was wondering if it could maybe be worked out. In the screenshot below, you'll see the depth I've added with a few alpha pixels (specifically, `(0, 0, 0, .125)` and `(0, 0, 0, .25)`). These pixels are rendering on the block as ItemStack form, but not in-world. 

![image](https://user-images.githubusercontent.com/3887324/61014942-c3903180-a357-11e9-8d7a-8bbb15b9d4cb.png)

Is this hard enough to fix that I should just drop the idea, or is there some hope? It's not by any means a big deal, and I know it's a lot harder since the 1.8.x update to make overlaid block textures, but just thought I'd ask.

**Comment by Aang23** [comment]
Does setting `"alphaOverlay": true,` works?
If it does (and I bet it'll), that's a super easy fix.

**Comment by oitsjustjose** [comment]
I actually don't see that option, is it in the config?

**Comment by Aang23** [comment]
It'll be in the Geolosys .json file. See https://github.com/Aang23/UndergroundBiomesConstructs/wiki/Adding-Ores-from-other-Mods

**Comment by Aang23** [comment]
Did that work?

**Comment by oitsjustjose** [comment]
I haven't had a chance to test either, but I assume that it works! I didn't realize that there were so many features available, but I assume they work!
