### ISSUE TITLE
[Request] UB-fy geolosys ores

### ISSUE THREAD

**Issue by ghost** [Aang23/UndergroundBiomesConstructs#12]
Geolosys ores are not recognised by UBC? If you are so inclined would you mind adding them if possible?

**Comment by Aang23** [comment]
No problems ! I'm gonna add them.

**Comment by Ash70** [comment]
I noticed this is something I could do myself. So I did. I'm attaching the json and textures in a zip. I do not know what license the original textures have and if redist like this is allowed?
[geolosys.zip](https://github.com/Aang23/UndergroundBiomesConstructs/files/2499017/geolosys.zip)
