### ISSUE TITLE
UBForceReProcessEvent does nothing because WorldGenManager is never registered as a listener

### ISSUE THREAD

**Issue by legendblade** [Aang23/UndergroundBiomesConstructs#120]
Currently, the new event added to force UB to reprocess a chunk for ores doesn't fire, because currently WorldGenManager is never registered on the event bus, only DimensionManager, which then forwards most events to WorldGenManager.

If the reprocess event could be moved up to DimensionManager, or WorldGenManager get registered on the event bus, that would be great, though I worry that the other subscribed events on WorldGenManager probably shouldn't get called anymore.

Thank you.

**Comment by Aang23** [comment]
Oh yeah, that something I should do... 
Note that this event is only meant to be posted on MinecraftForge.EVENT_BUS by other mods, not listened to.
