### ISSUE TITLE
Unable to craft vanilla button from vanilla stone

### ISSUE THREAD

**Issue by LemADEC** [Aang23/UndergroundBiomesConstructs#122]
As of 1.12-1.3.6, you need a UBC stone to craft an UBC button to craft a vanilla button.
This doesn't work when your overworld is pure vanilla and UBC stones are in other dimensions.
Consider adding a vanilla stone to vanilla button recipe.

**Comment by Aang23** [comment]
Wel I'll probably redo the whole recipe thing since it's pretty broken.

**Comment by Aang23** [comment]
Added a stone -> stone button recipe.
