### ISSUE TITLE
Green schist bugged

### ISSUE THREAD

**Issue by SpGilbert** [Aang23/UndergroundBiomesConstructs#125]
When you place green schist after grabbing it from jei it turns into vanilla andesite but the monster egg variant of it works fine.

**Comment by Aang23** [comment]
Could you provide like a video / gif of that issue?

**Comment by SpGilbert** [comment]
ok will do that in a bit.

**Comment by SpGilbert** [comment]
unable to replicate. not sure if it is because I'm using a different world.

**Comment by Aang23** [comment]
Probably a bug on your end or from another mod. Couldn't reproduce...
