### ISSUE TITLE
GrimPack Support

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#128]
The mod [GrimPack](https://www.curseforge.com/minecraft/mc-mods/grim-pack) adds in Uranium Ore, which hurts you when broken. The mod also adds in Oil Ore, Aluminum Ore, Black Diamond Ore, Element 115 Ore, and Randomite Ore.

**Comment by WenXin20** [comment]
Here are the Ore Textures:
Aluminum:
![aluminum_ore](https://user-images.githubusercontent.com/12000593/62349867-96eab800-b4c6-11e9-9b52-535788dbb4d0.png)
Black Diamond:
![black_diamond_ore](https://user-images.githubusercontent.com/12000593/62349883-9ce09900-b4c6-11e9-9554-417089828533.png)
Element 115:
![element_115_ore](https://user-images.githubusercontent.com/12000593/62349893-a36f1080-b4c6-11e9-8c89-016f6c6e99fe.png)
Oil:
![oil_ore](https://user-images.githubusercontent.com/12000593/62349901-aff36900-b4c6-11e9-956c-46077402653b.png)
Randomite:
![randomite](https://user-images.githubusercontent.com/12000593/62349911-b550b380-b4c6-11e9-9bd5-f0fdce352ca4.png)
Uranium:
![uranium_ore](https://user-images.githubusercontent.com/12000593/62349919-b97cd100-b4c6-11e9-9d04-274ef13958c3.png)
[grimpack.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3459916/grimpack.txt)

**Comment by Aang23** [comment]
No it's just close to the background's color.
