### ISSUE TITLE
UG's Walls won't connect to Vanilla's Walls

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#137]
Forge v14.23.5.2838
Underground Biomes v1.3.6

Vanilla Cobblestone Walls will connect to UG's Walls, but UG's Walls won't connect to Vanilla Walls, leaving an odd looking gap.

![2019-08-11_20 06 16](https://user-images.githubusercontent.com/12000593/62842314-e3788500-bc76-11e9-93ca-a53d3eb3f06c.png)

**Comment by Aang23** [comment]
*Related to this button bug...*
