### ISSUE TITLE
Community Mod Support

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#141]
The [Community Mod](https://www.curseforge.com/minecraft/mc-mods/community-mod) adds in a couple of really silly ores for 1.12.2.

[community_mod.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3492745/community_mod.txt)

Poke Ore (Animated):
[poke_ore.png.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3492736/poke_ore.png.txt)(Rename to .mcmeta)
![poke_ore](https://user-images.githubusercontent.com/12000593/62869389-646a6780-bcdd-11e9-9082-df1c525734c6.png)
Squirrel Ore: 
![squirrel_ore](https://user-images.githubusercontent.com/12000593/62869497-9a0f5080-bcdd-11e9-99b9-34abcd70e151.png)

**Comment by Aang23** [comment]
*Silly but Forge-humour related*
