### ISSUE TITLE
More Modded Support

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#143]
Here are multiple mods that don't have default UG support yet. I have added both the texture and json files, and provided the link to each mod.
- [Star Wars](https://www.curseforge.com/minecraft/mc-mods/star-wars-mod-by-danirus) adds in the animated Kyber Crystal Ore: ![ore_crystal](https://user-images.githubusercontent.com/12000593/62877983-d0ed6280-bced-11e9-96de-3a21254ad4b1.png)
     - [ore_crystal.png.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493296/ore_crystal.png.txt) (Change to .mcmeta)
     - [starwars.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493441/starwars.txt)
- [Custom Ideas](https://www.curseforge.com/minecraft/mc-mods/custom-ideas) adds in Silversteel Ore: ![silversteel_ore](https://user-images.githubusercontent.com/12000593/62876805-5e7b8300-bceb-11e9-8fe1-6c7ee957e787.png)
  - [customideas.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493444/customideas.txt)
- [Dartcraft Reloaded](https://www.curseforge.com/minecraft/mc-mods/dartcraft-reloaded) adds in the Power Ore: ![orepower](https://user-images.githubusercontent.com/12000593/62876940-a8646900-bceb-11e9-937e-e52d08bd0b53.png)
    - [dartcraftreloaded.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493448/dartcraftreloaded.txt)
- [Floricraft](https://www.curseforge.com/minecraft/mc-mods/floricraft) adds in the Salt Ore: ![ore_salt](https://user-images.githubusercontent.com/12000593/62877553-e4e49480-bcec-11e9-8884-4e643e04075c.png)
    - [floricraft.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493452/floricraft.txt)
- [Mo' Glowstone](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone) adds in the Glowstone Ore: ![glowstone_ore](https://user-images.githubusercontent.com/12000593/62877710-4278e100-bced-11e9-90d7-489a10cba2c0.png)
    - [moglowstone.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493454/moglowstone.txt)
- [Mubble](https://www.curseforge.com/minecraft/mc-mods/mubble) adds in Vanadium: ![vanadium_ore](https://user-images.githubusercontent.com/12000593/62877752-5886a180-bced-11e9-94a3-43945c11affe.png)
    - [mubble.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493455/mubble.txt)
- [Pyrotech](https://www.curseforge.com/minecraft/mc-mods/pyrotech) adds Dense Coal and Fossil Ores: ![dense_coal_ore](https://user-images.githubusercontent.com/12000593/62877824-7b18ba80-bced-11e9-8930-70bbb3df7bac.png) ![fossil_ore](https://user-images.githubusercontent.com/12000593/62877834-7eac4180-bced-11e9-8b99-203c30835f2c.png)
    - [pyrotech.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493458/pyrotech.txt)
- [Scaling Health](https://www.curseforge.com/minecraft/mc-mods/scaling-health) adds inthe Heart Crystal Ore: ![crystalore](https://user-images.githubusercontent.com/12000593/62877935-b87d4800-bced-11e9-8726-779ea7213b58.png)
    - [scalinghealth.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493459/scalinghealth.txt)
- [Worlds Retold](https://www.curseforge.com/minecraft/mc-mods/worlds-retold) adds in the Cryonite Ore: ![cryonite_ore](https://user-images.githubusercontent.com/12000593/62879560-fdef4480-bcf0-11e9-9b1a-433a5a7452bf.png)   [DONE]
    - [worldsretold.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493463/worldsretold.txt)
- [Treasure 2](https://www.curseforge.com/minecraft/mc-mods/treasure2) adds in Ruby and Sapphire Ores: ![ruby_nugget](https://user-images.githubusercontent.com/12000593/62878203-3d686180-bcee-11e9-92d2-5182a5236974.png) ![sapphire_nugget](https://user-images.githubusercontent.com/12000593/62878211-41947f00-bcee-11e9-8b9b-27dc9edc135e.png) [DONE]
    - Treasure 2 has multiple textures for both ores, but only two texture files.
    - [treasure2.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3493464/treasure2.txt)

**Comment by Aang23** [comment]
*I can't thank you enough for asking for mod support like this. The fact you provide the overlays & jsons makes my work so much easier... Thanks!*
