### ISSUE TITLE
Resource pack containing old sand textures

### ISSUE THREAD

**Issue by NickelHub** [Aang23/UndergroundBiomesConstructs#145]
Because of complaints, the old sand textures bad been removed, and had been replaced by some similar to regular sand texture. 
It would be nice if the old textures are put into a resource pack. Thus, everyone who like them can use it.

**Comment by Aang23** [comment]
I'll do that pretty soon. (In both 1.12.2 & 1.14.x)

**Comment by Aang23** [comment]
[undergroundbiomes-alternatives-1.12.2-1.zip](https://github.com/Aang23/UndergroundBiomesConstructs/files/3498500/undergroundbiomes-alternatives-1.12.2-1.zip)
Soon to be on Curseforge.

**Comment by NickelHub** [comment]
Thank you.
