### ISSUE TITLE
PLEASE make it so we can craft items without regular cobblestone

### ISSUE THREAD

**Issue by Niosquare** [Aang23/UndergroundBiomesConstructs#146]
It's very annoying because I can't do anything without finding a village and destroying all the cobblestone houses. Or having to cheat.

**Comment by Aang23** [comment]
1.12.2 / 1.14.x ?
Use the recipe to get vanilla cobble?

**Comment by Niosquare** [comment]
> 1.12.2 / 1.14.x ?
> Use the recipe to get vanilla cobble?

I'm in 1.14.4. I'm new to this mod so didn't know. Sorry! But it would be nice if you could craft regular cobble items using the custom modded one. Thanks for the help!

**Comment by Aang23** [comment]
That's why it's still alpha... Didn't work tagging out yet. (new oredict)
You can get vanilla cobble by using a 2x3 pattern in a crafting table.

**Comment by Niosquare** [comment]
Thanks for explaining! Have a great day!

**Comment by Aang23** [comment]
Should be fixed now.
