### ISSUE TITLE
[Mod Support] Survivalist

### ISSUE THREAD

**Issue by thegamerx1** [Aang23/UndergroundBiomesConstructs#147]
Please add support for this mod i dont want to remove UnderGroundBiomes :(

Survivalist issue: https://github.com/gigaherz/Survivalist/issues/93
wiki: https://github.com/gigaherz/Survivalist/wiki
curseforge: https://www.curseforge.com/minecraft/mc-mods/survivalist

**Comment by Aang23** [comment]
What kind of compatibility would be required? Ores? Stones? etc?

**Comment by thegamerx1** [comment]
ores now should drop like smaller ores and cobblestone should drop rocks to make cobblestone with clay
going to be editing this comment with more things

**Comment by thegamerx1** [comment]
havent already checked but is there anyway to make blocks drop the original block's items

**Comment by Aang23** [comment]
You can convert them back to vanilla cobble. Drops could be changed through some CraftTWeaker addon.
Though I could add an option to make them drop vanilla cobble instead. If yes, please make a separate issue.

**Comment by Aang23** [comment]
Also open on issue on Survivalist's issue tracker about this request. Some things would be better of handled on their side.

**Comment by thegamerx1** [comment]
Where's that lol

**Comment by Aang23** [comment]
https://github.com/gigaherz/Survivalist/issues
