### ISSUE TITLE
Buttons not showing properly

### ISSUE THREAD

**Issue by syelents** [Aang23/UndergroundBiomesConstructs#149]
[Minecraft 1.14.4 Version 1.0-44]
When you place any of the Underground Biome buttons on the ground, the button appears as if it were on a wall. You cannot hit the button, there is an outline of where the button should be that can be hit.
![UBButtonBug](https://user-images.githubusercontent.com/54427152/63756874-1f226a00-c887-11e9-914e-7bfb132651a6.gif)

**Comment by Aang23** [comment]
Thanks for your report!
