### ISSUE TITLE
MysticalWorld ores have missing textures

### ISSUE THREAD

**Issue by scribbler957** [Aang23/UndergroundBiomesConstructs#151]
MysticalWorld (Mystic World on Curse) ores have the magenta and black when appearing in UB stone. I've been playing with the json, but haven't had any luck fixing it.

**Comment by scribbler957** [comment]
I did that and tried mysticalWorld in case there was some caps sensitivity somewhere. The json is valid and resembles enderore.json, which does work. I even tried changing the meta to 0 because I thought HWYLA showed @0. I'm digging through the  Mystical World code trying to find where the ores are actually defined, but I'm not familiar with the APIs so they could be indirectly created for all I know.

**Comment by scribbler957** [comment]
I think I found the ore block creation [here](https://github.com/MysticMods/MysticalWorld/blob/190d4591b9ad32ebac3661740d05471697dfaaa9/src/main/java/epicsquid/mysticalworld/materials/Metal.java#L231) but that seems to indicate that copper_ore is the correct name. I'm going to keep digging, maybe go into MysticalLib...

**Comment by scribbler957** [comment]
I figured, but I looked to see if there was something simple like a typo.

**Comment by Dimentive** [comment]
Why was this closed? This was not fixed.
