### ISSUE TITLE
Incorrect Overlay Texture Definitions for MysticalWorld, StarWars, & Grimpack

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#152]
Underground Biomes v1.3.7
- For the `grimpack.json`, the overlay definition doesn't match up with the texture file names and the directory is pointing to `byg` instead of `grimpack`.
- For the `mysticalWorld.json`, the overlay definition for the ores repeats `undergroundbiomes:` twice.
- For the `starwars.json`, I'm not entirely sure what's incorrect, but it could be the .mcmeta file.

Since these are invalid, ores are appearing as purple and black cubes.

**Comment by Aang23** [comment]
*Oversights... Sorry!*
GrimPack & MysticalWorld shoud be good now (test the jenkins build out?), and I'm gonna take a deeper look at StarWars.

**Comment by Aang23** [comment]
`It's fixed now. You can test it out with this build : https://jenkins.altillimity.com/job/Underground%20Biomes/80/artifact/build/libs/UndergroundBiomesConstructs-1.12-1.3.7-80.jar

**Comment by Aang23** [comment]
I'll make sure it works too.

**Comment by WenXin20** [comment]
Just tested the build, but Mystical World and Grimpack still have missing textures. Star Wars is working though.

**Comment by Dimentive** [comment]
Why was this closed?
