### ISSUE TITLE
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by DatrixTHLK** [Aang23/UndergroundBiomesConstructs#154]
Minecraft: 1.14.4
Forge (BETA): 28.0.74
Underground Biomes: 1.0-44
Crash: https://gist.github.com/DatrixTHLK/fdac7e4c9fe52f5851adf3f730c7c11f
I'm not exactly sure this is your mods fault or if forge updating broke this, but here it is anyway...

**Comment by Mahtaran** [comment]
This is due to the Forge update indeed. Stick to version before 28.0.62 for now. The latest compatible Forge version is 28.0.58.

**Comment by DatrixTHLK** [comment]
I see, thanks for the info.

**Comment by Aang23** [comment]
Fixed.

**Comment by DatrixTHLK** [comment]
Thanks for the response and fix!
