### ISSUE TITLE
replaces core blocks with modded ones

### ISSUE THREAD

**Issue by 84f** [Aang23/UndergroundBiomesConstructs#155]
haven't found a single cobblestone which really messes with advancements

**Comment by Aang23** [comment]
Wdym? 1.14.4? 1.12.2?

**Comment by 84f** [comment]
im on 1.14.4 and there’s pretty much no core blocks remaining and I can’t even use some of the blocks for crafting recipes

**Comment by Aang23** [comment]
You can actually convert them back to vanilla variant using a 2x3 pattern.
Oredicting (tagging) and overall compatibility isn't done yet

**Comment by 84f** [comment]
what do you mean 2x3 pattern
