### ISSUE TITLE
New Maven requires auth

### ISSUE THREAD

**Issue by oitsjustjose** [Aang23/UndergroundBiomesConstructs#159]
My Gradle builds are failing with a `401` status when hitting [`https://maven.altillimity.com/content/groups/maven/exterminatorjeff/undergroundbiomes/undergroundbiomes/1.3.7-57-1.12.2/undergroundbiomes-1.3.7-57-1.12.2.pom`](https://maven.altillimity.com/content/groups/maven/exterminatorjeff/undergroundbiomes/undergroundbiomes/1.3.7-57-1.12.2/undergroundbiomes-1.3.7-57-1.12.2.pom).

Is there a way to get a key for authentication? For now, I've had to comment out the dependency in my build file.

Cheers!

**Comment by oitsjustjose** [comment]
I missed the "sign up" part :| - that being said, I still can't access it just with a different issue

**Comment by Aang23** [comment]
Uh no forget about it I just forgot to put back the right ip address in my reverse proxy setup... You can now use the repo like before. (It was redirecting to my gitlab... Derp)
Sorry for the inconvenience!
