### ISSUE TITLE
Upper Slab Displays Incorrectly w/ Hwyla

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#160]
Minecraft v1.12.2
Forge v14.23.5.2838
[Hwyla](https://www.curseforge.com/minecraft/mc-mods/hwyla) v1.8.26-B41
UBC v1.3.7

As the title says, looking at a UBC slab placed in the upper half of a block displays a missing texture with Hywla.
![2019-09-03_20 09 43](https://user-images.githubusercontent.com/12000593/64379623-ee63d280-cff4-11e9-97bc-46f3ee60205b.png)

**Comment by Aang23** [comment]
Should be fixed now.
