### ISSUE TITLE
Immediate Crash After Launch

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#161]
Minecraft v1.14.4
Forge v28.0.95
UBC v1.0-44

I got this crash immediately after pressing the play button of the Minecraft luancher.
[Crash Report](https://gist.github.com/WenXin20/28aeab37beec97ae37185cbce043b6fb)

**Comment by Aang23** [comment]
Forge changed some classes again...

**Comment by Aang23** [comment]
Updated forge and tried it out... Seems to work!
Closing for now, if the issue persists, I'll reopen.
