### ISSUE TITLE
[1.14.4] Druidcraft Mod Support

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#164]
[Druidcraft](https://www.curseforge.com/minecraft/mc-mods/druidcraft) is for 1.14.4 and adds in Amber, Fiery Glass, Moonstone, and Rockroot Ores.

[druidcraft.zip](https://github.com/Aang23/UndergroundBiomesConstructs/files/3611935/druidcraft.zip)

**Comment by Aang23** [comment]
Added but non-working as of now. See https://github.com/Aang23/UndergroundBiomesConstructs/issues/165
