### ISSUE TITLE
UBC Cobblestone Items Missing #forge:cobblestone

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#167]
Minecraft v1.14.4
Forge v28.1.8
UBC v1.0-47

UBC Cobblestone and other blocks/items are missing their forge tags for item drops. Both blocks and the corresponding items need a forge tag to be properly compatible with other mods.

Currently, this mean that most recipes that use #forge:cobblestone or any others are not compatible with UBC Cobblestone, gravel, sand, etc.

See SilentChaos512/Silent-Gear#64 for a bit more info and the original post.

**Comment by Aang23** [comment]
Expect a fix very soon!
