### ISSUE TITLE
UBOre should use BlockRenderLayer.SOLID

### ISSUE THREAD

**Issue by srs-bsns** [Aang23/UndergroundBiomesConstructs#172]
Is there a reason why `UBOre#getRenderLayer` is returning `BlockRenderLayer.CUTOUT_MIPPED`?
https://github.com/Aang23/UndergroundBiomesConstructs/blob/1.14.2/src/main/java/com/aang23/undergroundbiomes/blocks/UBOre.java#L60-L63
This should probably be returning `BlockRenderLayer.SOLID`.

Using `CUTOUT_MIPPED` leads to:
![2019-09-25_02 01 03](https://user-images.githubusercontent.com/8453133/65574187-c3f19f00-df3a-11e9-9867-cf3a3b7be7cd.png)

**Comment by Juuxel** [comment]
I don't think the solid render layer can render transparent layered textures (which UB uses afaik).

**Comment by Aang23** [comment]
`BlockRenderLayer.Solid` can't do alpha blending with non 1 or 0 values... Causing that kind of awkwardness : 
![2019-09-25_20 01 20](https://user-images.githubusercontent.com/23421917/65627275-5479bf00-dfcf-11e9-9038-f9ef025c853e.png)

Though I could probably make SOLID the default and allow specifying CUTOUT_MIPPED on required ores only.
