### ISSUE TITLE
Startup game crash rendering overlay

### ISSUE THREAD

**Issue by slard3** [Aang23/UndergroundBiomesConstructs#174]
[crash-2019-09-25_22.23.47-client.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3655442/crash-2019-09-25_22.23.47-client.txt)

**Comment by Aang23** [comment]
Doesn't seem to be UBC-related : 
```
java.lang.NullPointerException: Rendering overlay
	at com.oblivioussp.spartanshields.util.ConfigHandler.onConfigLoad(ConfigHandler.java:369) ~[?:1.14.4-2.0.0-beta-1] {}
```
I'd look into Spartan Shields though.

**Comment by slard3** [comment]
Thanks for your response.
I'm pretty sure it isn't spartan shields because when i removed your mod, the game runs smoothly (i'll try remove spartanshields and run UB afterwards to check this anyway).
this crash happened after i started to play around with json files to add ores from other mods (specifically simply platinum's platinum ore). I don't know how to code properly, so this crash probably is my own fault.
Regardless, thank you

**Comment by Aang23** [comment]
I can't see anything related to UBC in the logs...

Though if you're getting crashes after altering .jsons, please post them here! I didn't document 1.14's new format and thus it's also kind of my fault.
