### ISSUE TITLE
Crashes upon loading worlds with DesertLands.

### ISSUE THREAD

**Issue by ALPHANUMERIC1** [Aang23/UndergroundBiomesConstructs#18]
Underground Biomes is trying to use its world gen manager on the dimension in DesertLands when it shouldn't, causing a crash upon world loading.

[Link to DesertLands](https://minecraft.curseforge.com/projects/desertlands)

[Link to crash log](https://pastebin.com/23MsHX16)

**Comment by ALPHANUMERIC1** [comment]
Got it.

**Comment by Aang23** [comment]
I just looked closely at that bug, and this should be fixed on DesertLands' side.

**Comment by ALPHANUMERIC1** [comment]
Thanks.

**Comment by Aang23** [comment]
I'll close this since that should get fixed on their side. But I'll reopen it if necessary.
