### ISSUE TITLE
What is the level Type?

### ISSUE THREAD

**Issue by EpochHolocene** [Aang23/UndergroundBiomesConstructs#181]
Minecraft: 1.12.2
Forge: 14.23.5.2768
UB: 1.2.1

Hi, I'm having server issues with my server using this mod, and the help desk is asking what level type Underground Biomes is. I don't really know what this means.

**Comment by Aang23** [comment]
What!? Could you provide a screenshot? UBC doesn't need a level type.

**Comment by EpochHolocene** [comment]
Thats what i was thinking, 
![image](https://user-images.githubusercontent.com/56230885/66272623-2e0f1b80-e83a-11e9-932f-b681ed10fdb0.png)

**Comment by Aang23** [comment]
Then use whatever you want like large biomes / default / flat etc.

**Comment by EpochHolocene** [comment]
Thanks, I have a feeling there was miscommunication and UBC is not what is causing my server problems.

**Comment by Aang23** [comment]
Well if you've got a crash report / logs feel free to post them here (pastebin/hastebin).
