### ISSUE TITLE
Vanilla Moss Stone recipe is missing (1.12.2)

### ISSUE THREAD

**Issue by MattRoxx** [Aang23/UndergroundBiomesConstructs#185]
Hello, with Underground Biomes the vanilla recipe for moss stone ( cubblestone + Vines) is gone.

To reproduce:
Install Minecraft 1.12.2, latest Forge (1.12.2 - 14.23.5.2847) and Underground Biomes Constructs 1.12-1.3.7.

Thank you for your attention!

**Comment by Aang23** [comment]
I'll add it back in the next release.
In the meantime craft UBC's moss stone and then convert it back to its vanilla variant using the standard 2x2 pattern.
