### ISSUE TITLE
ClassCastException in JSON parsing causing load failure

### ISSUE THREAD

**Issue by srs-bsns** [Aang23/UndergroundBiomesConstructs#186]
In `defaults.zip`, which gets extracted to `config/undergroundbiomes` the `ore/minecraft.json` file contains the property `alphaBlend` which is added as a JSON primitive (boolean, as it should be), but when the file is parsed in [UBOreConfigManager.java#L81](https://github.com/Aang23/UndergroundBiomesConstructs/blob/1.14.2/src/main/java/com/aang23/undergroundbiomes/registrar/UBOreConfigManager.java#L81)...
```java
    ? Boolean.parseBoolean((String) oreConfig.get("alphaBlend"))
```
you are trying to parse a String to a boolean after trying to cast a boolean to String.

Because the call chain that leads to this is called from the constructor of the UB main class and has no exception handling, this causes UB to fail. This in turn causes the event bus to shut down although loading still continues due to an issue in Forge that doesn't halt loading, and eventually this will lead to a crash occuring later on that will likely get attributed to another mod trying to access some object that was never registered, such as in #174. (In my case, it was one of McJty's mods.)

```
[modloading-worker-0/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Failed to create mod instance. ModID: undergroundbiomes, class com.aang23.undergroundbiomes.UndergroundBiomes
java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
	at com.aang23.undergroundbiomes.registrar.UBOreConfigManager.readJsons(UBOreConfigManager.java:81) ~[?:1.0-62]
	at com.aang23.undergroundbiomes.registrar.UBOreConfigManager.setupConfigs(UBOreConfigManager.java:43) ~[?:1.0-62]
	at com.aang23.undergroundbiomes.registrar.UBOreRegistrar.initialSetup(UBOreRegistrar.java:70) ~[?:1.0-62]
	at com.aang23.undergroundbiomes.UndergroundBiomes.<init>(UndergroundBiomes.java:61) ~[?:1.0-62]
```

**Comment by Aang23** [comment]
*Why did I do that?*
