### ISSUE TITLE
Invalid texture path for MysticalWorld

### ISSUE THREAD

**Issue by LemADEC** [Aang23/UndergroundBiomesConstructs#188]
As of forge-14.23.5.2847 with UndergroundBiomesConstructs-1.12-1.3.7, the MysticalWorld amethyst ore overlay is seen a full purple or missing texture (depending on other mods present).
The related texture path isn't fully lowercase as `.../overlays/mysticalWorld/...` contains an uppercase W.
Issue is also reproduced with forge-14.23.5.2836.

**Comment by Dimentive** [comment]
Why was this closed? I’m having the same issue on the latest versions of both mods.
