### ISSUE TITLE
Broken Oredict

### ISSUE THREAD

**Issue by Mrthomas20121** [Aang23/UndergroundBiomesConstructs#191]
Oredict are broken in the UBC version that i use (1.3.7).
here the broken oredict and how to fix them to work with other mods:

- all UBC clay have the clay oredict when they should have blockClay oredict.
- limestone have the limestone oredict when it should have stoneLimestone oredict. 
- basalt have the basalt oredict when it should have stoneBasalt oredict. 
- marble have the quartz oredict when it shouldn't have it. it should also have stoneMarble
- all mossy cobblestone should have the blockMossy oredict to match vanilla cobblestone.

**Comment by Aang23** [comment]
That'll be fixed in the next release.
*Why was marble ever oredicted as quartz?*
