### ISSUE TITLE
[Suggestion] stone oredict

### ISSUE THREAD

**Issue by Mrthomas20121** [Aang23/UndergroundBiomesConstructs#192]
Add a special oredict to all stone.

here what i mean:

sedimentary stone will get the stoneSedimentary oredict.
metamorphic stone will get the stoneMetamorphic oredict.
Igneous stone will get the stoneIgneous oredict.

this allow modpack maker to make recipes that require a type of stone(sendimentary, metamorphic, igneous).

in the meantime, if anyone wants to do this for their modpack and can't wait for a release i have a crafttweaker script: 
```zs
var stoneSediment = <ore:stoneSedimentary>;
var stoneIgneous = <ore:stoneIgneous>;
var stoneMetamorphic = <ore:stoneMetamorphic>;

stoneSediment.add(<undergroundbiomes:sedimentary_stone:*>);
stoneIgneous.add(<undergroundbiomes:igneous_stone:*>);
stoneMetamorphic.add(<undergroundbiomes:metamorphic_stone:*>);
```

**Comment by Aang23** [comment]
Will be in the next release!
