### ISSUE TITLE
Improve Clay/Gravel/Sand configurations

### ISSUE THREAD

**Issue by LemADEC** [Aang23/UndergroundBiomesConstructs#193]
As of 1.12-1.3.7, I've noticed a few improvement opportunities in the Clay/Gravel/sand configurations:
1- small typo: replacClay should be replaceClay
2- unlike gravel and sand, I couldn't find a biome restriction for clay
3- to improve compatibility with plants, could we have an option to disable replacement on the top layer (see for example Zawa adding underwater plants that don't support UBC gravel) ?

**Comment by AngelaYuzyk** [comment]
I would add 

4- There should be an additional `ReplaceSandstoneExcludedBiomes` option, or at least `ReplaceSandExcludedBiomes` should apply to sandstone as well

**Comment by Aang23** [comment]
I didn't think a biome restriction was necessary for clay as first, but that's definitely gonna be added.
Thanks!
