### ISSUE TITLE
[1.12.2] Roots compatibility broken

### ISSUE THREAD

**Issue by noobanidus** [Aang23/UndergroundBiomesConstructs#194]
I presume whatever changes I made recently in converting from a horrendous quantity of baked models back to using standard blockstate files has caused issues -- potentially because there is no longer a model? (Although I feel as though one should be automatically generated).

Case in point: ![](https://i.imgur.com/knqBT8b.png)

**Comment by Aang23** [comment]
I think that's more of a problem on my side, models are supposed to be auto-generated but depends on a proper .json file.

**Comment by Qualma** [comment]
I have the same bug, please fix <3

**Comment by Aang23** [comment]
I just tested this, and everything seems fine!
