### ISSUE TITLE
[1.12.2] Typo in baseminerals.json

### ISSUE THREAD

**Issue by NickelHub** [Aang23/UndergroundBiomesConstructs#2]
There is a typo in the standard .json. Niter is writte Nither, which results in no ore variants. I fixed it for you.

[baseminerals.zip](https://github.com/Aang23/UndergroundBiomesConstructs/files/2405380/baseminerals.zip)

The typo in the assets file is still present.

**Comment by Aang23** [comment]
Oh... That from the older repo I forked it from. Fixed in dev, coming soon.
