### ISSUE TITLE
[1.12.2] Ore required harvest level is no working mod integration

### ISSUE THREAD

**Issue by skicek** [Aang23/UndergroundBiomesConstructs#200]
General Information
Describe the bug:
Problem is with harvest level. If ore is level 4 so it should not be possible to mine it with e.g iron pickaxe, but you are. In short you are able to mine any ore with any pickaxe and receive ore from it.

To Reproduce:

Find some rare ore (that normally would be impossible to mine with wood pickaxe)
Mine it with woodpickaxe
You will receive an ore from it
Expected behavior:
not receive ore

Environment Versions
Versions:

Metallurgy: UndergroundBiomesConstructs-1.12-1.3.7
Conflicting mod (if regarding mod integration): 
ThermalFoundation-1.12.2-2.6.3.27-universal
Metallurgy-4-Reforged-0.2.3

Forge: forge-1.12.2-14.23.5.2847-universal
Minecraft: 1.12.2

Crash Report (if available):
no crash report.

Latest Log (if necessary):
n/a

Additional Information
Screenshots (if available):
n/a

Additional context (optional):
problem is that if ore is from some mod like ThermalFoundation or Metallurgy (with these two I tested) and it is generated by UBC (when it have texture from UBC) you are able to mine it regardless of required level of pickaxe. 
If I spawn original ore from these mods, harvest level is applied. 
Notice also that vanilla ore is not affected by this. 
So only ores from mods which are generated by UBC are broken.

I tried to disable B:UBifyOres but it dont do anything, ore still have texture from UBC

**Comment by Aang23** [comment]
Thanks... Thought I had this fixed already.
