### ISSUE TITLE
[1.12.2] Exclude mod

### ISSUE THREAD

**Issue by Nelly1234567** [Aang23/UndergroundBiomesConstructs#202]
Is there a way I can exclude/disable a mod from being included or at least blocks from being included in this mod? Two mods I have (Thermal Foundation and MysticalWorlds) are creating missing texture blocks.

 I could fix the Thermal foundation one but I can't disable it or anything else. This is causing problems because I can't get MysticalWorlds blocks to not have missing textures with UGB and I can't fix them via the config files.

If there is no way to disable mods from being included then please add an option for it if possible.

**Comment by bookerthegeek** [comment]
What version of minecraft are you playing? I can pastebin the configs to dd those textures for you.

**Comment by Nelly1234567** [comment]
1.12.2

**Comment by Aang23** [comment]
This can be disabled by editing the .json files in the config folder.

**Comment by Nelly1234567** [comment]
Thank you, I did not realize removing everything from the file would work, I tried everything but that.

**Comment by sealchan1** [comment]
This is the work-around I was looking for until the latest missing texture issue can be resolved.
