### ISSUE TITLE
Placing ore blocks in offhand randomizes rock type/possible crashes.

### ISSUE THREAD

**Issue by UnlimatedStone9** [Aang23/UndergroundBiomesConstructs#203]
When you have an ore block in your off hand and place it down there's a chance it will change it's metadata and in turn rock type, this can potentially crash the game too if an invalid metadata is chosen.
This happened when placing down a Red Granite type Hematite Ore from the 'Geolosys' mod, but could occur with other ores.

**Comment by Aang23** [comment]
Could you provide a crash report?

**Comment by UnlimatedStone9** [comment]
I haven't been able to replicate the crash recently, and this was reported a while back so I'm not even sure where the client this was done in is.
I'm certain it did crash, though even if not, incorrect block metadata has been known to crash the game (at least in my experience) with numerous mods. So it might've just been an assumption.

**Comment by Aang23** [comment]
Fixed!
