### ISSUE TITLE
No generating GregTech community Edition ores!

### ISSUE THREAD

**Issue by MrProton657** [Aang23/UndergroundBiomesConstructs#21]
Thats it, no GTCE ore veins are generating with UBC(it worked on 1.7.10). Please help quick. Thanks. MrProton

**Comment by Aang23** [comment]
Could you tell me more informations ? What versions were you using ? Using which world generator, etc.

**Comment by MrProton657** [comment]
thanks for reply.
Generator: Biomes o plenty
UBC version: 1.3.0
GTCE version: 1.0.124
I also asked the GTCE developers to do something here: https://github.com/GregTechCE/GregTech/issues/334#issuecomment-449502737
But they sad that I can somehow the generation in the configs (I don't understand in which config from what mod), but the the ores would be stone vanilla versions now. So I think that feature than is your work and maybe a feature for v1.3.1.
So thank you and I hope we get a solution soon.

greetings
MrProton

**Comment by MrProton657** [comment]
Guys I need help quick!

**Comment by Aang23** [comment]
I'm gonna be trying on my side.

**Comment by MrProton657** [comment]
Thank you

**Comment by Aang23** [comment]
I'll close this since GregTech's dev says there's no issue. Please ask me to reopen if necessary !
