### ISSUE TITLE
error during the common_setup event phase

### ISSUE THREAD

**Issue by Reael** [Aang23/UndergroundBiomesConstructs#215]
So the error only occures as soon as I have the undergroundbiomes mod in my modfolder (tried every version there is for 1.14.4) but it always lists another mod.
Sometimes it says _Charms: error during the common_setup event phase_
sometimes _Pams: error during the common_setup event phase_
sometimes _Biomes'o'Plenty: error during the common_setup event phase_
and sometimes _undergroundbiomes: error during the common_setup event phase_
I assume it has something to do with undergroundbiomes since the error does not occur at all when I delete it from my mods folder. I'm no programmer by any means and I tried googling everything but I can't make sense of this at all, so I attached the error log. Hope someone can help me.
[latest_MC_Crashlog.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/4238631/latest_MC_Crashlog.txt)

**Comment by Syndaryl** [comment]
This is happening because UBC is crashing the event bus - the next mod to try to use the event bus finds it shut down, and then we her the general crash

**Comment by Reael** [comment]
This makes a lot of sense. Is there a way to fix this?

**Comment by Reael** [comment]
I found this in the closed cases while trying to find a solution for my problem [ClassCastException in JSON parsing causing load failure](https://github.com/Aang23/UndergroundBiomesConstructs/issues/186). It sounds just like the problem I'm encountering so I thought I drop it here since the other issue is closed. I don't think it's still the same issue in the same code line but probably something similar.

**Comment by Aang23** [comment]
I'll take a look I thought that was fixed... Thanks for reporting!

**Comment by Aang23** [comment]
This is not caused by UBC according to this crash report, I only see Pam's referenced.

**Comment by Reael** [comment]
Hm weird, it still came up after removing Pams. Could it be Pams created an error UBC got stuck in even after removing pams? Oh well, also reported it to Pams, once updates are out I'll try again :)
