### ISSUE TITLE
Limestone Slab Texture issue

### ISSUE THREAD

**Issue by CalaMariGold** [Aang23/UndergroundBiomesConstructs#216]
**Describe the bug**
Limestone slabs textures are missing if mined or looking at through WAILA, it is not
missing any textures when placed or looking at through the inventory.

**To Reproduce**
Mine limestone slab. Also, place a limestone slab, look at the bottom left for the WAILA information and notice the missing texture.

**Expected behavior**
For them to not have a missing texture.

**Screenshots:**
https://i.imgur.com/JYk6Ajb.png
https://i.imgur.com/DEi72zb.png

**Comment by Aang23** [comment]
So my fix didn't work... Thanks for reporting!
