### ISSUE TITLE
ArchitectureCraft and UBG compatabilty issue.

### ISSUE THREAD

**Issue by gswindle76** [Aang23/UndergroundBiomesConstructs#217]
Not sure which is the issues here but placing cobblestone/soapstone stairs in offhand I crash the game and receive the error....

`The game crashed whilst ticking entity
Error: java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=light, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateContainer{block=undergroundbiomes:metamorphic_stone, properties=[type]}`

**Comment by Aang23** [comment]
I was unable to reproduce the issue myself despite trying your exact scenario.
Probably fixed it along with another bug.
