### ISSUE TITLE
Black granite Coal Ore is indistinguishable from black granite

### ISSUE THREAD

**Issue by Deshiba** [Aang23/UndergroundBiomesConstructs#24]
Title pretty much says it all. For visual aid see the screenshot below.

![2018-12-27_11 13 41](https://user-images.githubusercontent.com/10565800/50476520-b669b180-09c8-11e9-9a0f-268f523f16db.png)

**Comment by Aang23** [comment]
The only way to fix that would be a texture change... I won't be fixing that, as some issue needs to be fixed before that.
Thanks for reporting!

**Comment by Aang23** [comment]
That's will surely not be modified... If you really want to do that a texturepack could fix it.
![2019-02-24_13 20 24](https://user-images.githubusercontent.com/23421917/53299146-14830b80-3837-11e9-90ae-811ec1cc98f4.png)
