### ISSUE TITLE
[1.12] Grid-like generation with external ore generators (OSV)

### ISSUE THREAD

**Issue by Foreck1** [Aang23/UndergroundBiomesConstructs#241]
Using another mod that creates ore variants and handle generation such as [Ore Stone Variants](https://www.curseforge.com/minecraft/mc-mods/ore-stone-variants) together with underground biomes alters ore generation in an undesirable way, creating a "grid" of ores across the world with parallel ore-less regions.
According to Personthecat—developer of Ore Stone Variants—"My current guess is that it may have to do with when UBC's stone gets placed in the world. There may be a conflict between the two generators around the same time, causing them to fight for placement."
Here's an image of intended oregen with vanilla stone types
![image](https://user-images.githubusercontent.com/47757429/91216628-4901ad00-e6e4-11ea-92f0-694fd9c71dfe.png)
And an image of what happens when UB is used alongside
![image](https://user-images.githubusercontent.com/47757429/91216894-ae559e00-e6e4-11ea-8bcf-8656f65d09b6.png)

This behavior also seems to vary across different biomes:
![image](https://user-images.githubusercontent.com/47757429/91217020-de9d3c80-e6e4-11ea-8d0c-eace9252de9a.png)
And persists in other Dimensions such as The Beneath: 
![image](https://user-images.githubusercontent.com/47757429/91217094-fa084780-e6e4-11ea-9e7d-ecbee7dd6066.png)

**Comment by LemADEC** [comment]
Not sure what the original issue was but, as of current version UBC 1.38, there's no ore generation at all with [Ore Stone Variants](https://www.curseforge.com/minecraft/mc-mods/ore-stone-variants) 5.14.  
According to OSV source code, non-vanilla stones aren't supported and, furthermore, the mod fails to call `isReplaceableOreGen()`, so at this point, it's mostly a bug on their side.

**Comment by Foreck1** [comment]
Since I could never fix this, I ended up replacing the world underground generation with a strata system using another mod and this one's stone two years ago. If you say this is on OSV's, there's no point to this issue anymore.
