### ISSUE TITLE
CURSEFORGE

### ISSUE THREAD

**Issue by kreezxil** [Aang23/UndergroundBiomesConstructs#27]
@Aang23 you now have full access to the CurseForge page for this mod and it now points to your resources here on this fork.

**Comment by Aang23** [comment]
Thanks !
I think that I'm gonna be transferring all the build I had posted on my fork's page, just to keep that clean and to ease the transition for modpacks.

**Comment by kreezxil** [comment]
as far as forking goes, I wouldn't bother with github transference, Kyeti's
is in some kind of special place of mind where doesn't even have time to
code anymore, which explains why he basically left minecraft and github.
and ofcourse zeno is nowhere to be found.

**Comment by Aang23** [comment]
I had already guessed why he left, even if I didn't know anything more than that. I just hope that everything's going well for him.
Zeno hasn't been seen in years now...

**Comment by kreezxil** [comment]
he didn't tell me why he left, he was really vague in it. But it did say
life was too hectic to have to worry about the project.

**Comment by Aang23** [comment]
I think I can close that now...
