### ISSUE TITLE
Feature Request: add support to UBify Quark's Speleothem blocks

### ISSUE THREAD

**Issue by Dulciphi** [Aang23/UndergroundBiomesConstructs#30]
Quark's Speleothem blocks are stalagmites and stalactites that appear underground in caves. They currently appear in vanilla stone variants.

Having these blocks textured according to the UBC stone they generate in/on would be excellent. 

[link to Vazkii's tweet showing Speleothem blocks](https://twitter.com/Vazkii/status/1025159087305187329)

**Comment by Aang23** [comment]
Here's a little image to show how that will look like.
![2019-01-05_12 09 09](https://user-images.githubusercontent.com/23421917/50723811-d3963280-10e2-11e9-80e1-f4348f2e6878.png)

**Comment by Aang23** [comment]
![2019-01-05_16 40 58](https://user-images.githubusercontent.com/23421917/50726300-6c40a880-110b-11e9-84b9-fe0d33091022.png)
![2019-01-05_16 41 21](https://user-images.githubusercontent.com/23421917/50726301-6cd93f00-110b-11e9-9d24-6108fab0746f.png)
![2019-01-05_16 42 03](https://user-images.githubusercontent.com/23421917/50726302-6cd93f00-110b-11e9-8f14-f2ef3f7fee5b.png)
That's it ! Thanks for the idea !

**Comment by Dulciphi** [comment]
That's great!
