### ISSUE TITLE
Geolosys file incomplete

### ISSUE THREAD

**Issue by IronPiston** [Aang23/UndergroundBiomesConstructs#33]
I was looking through the issues and noticed someone submitted a request for Geolosys support: https://github.com/Aang23/UndergroundBiomesConstructs/issues/12

I compiled the mod and noticed that support was still missing. I downloaded the .json file from that issue and added it to the config folder, and it works perfectly now.

I think the .json file for Geolosys wasn't properly added in.

**Comment by Aang23** [comment]
I'm gonna be taking a look at this. When I tested that worked fine.
