### ISSUE TITLE
Suggestion: add oredict entries for specific stone types

### ISSUE THREAD

**Issue by gryttr** [Aang23/UndergroundBiomesConstructs#4]
Currently all of the UBC stone types are oredicted as "stone". It would be nice to get some more specific oredict types in addition to that, to allow them to work in the recipes of other mods that add similar stone types (such as Quark's or Chisel's marble, basalt, and limestone).

**Comment by Aang23** [comment]
Good idea. This is something that bothered me during my last test gameplay... Will be added.

**Comment by Aang23** [comment]
I have added the "quartz", "limestone" and "basalt" oredict entry to their related block, I hope this will be enough. I'll let that open to be sure.

**Comment by Aang23** [comment]
I'll close that, hopefully the current oredict I added are enough. If not, reopen an issue. 
Thanks for the feature idea !
