### ISSUE TITLE
Add support for Thermal's Igneous Extruder

### ISSUE THREAD

**Issue by bookerthegeek** [Aang23/UndergroundBiomesConstructs#40]
# Heyo!
Thermal Expansion adds in an [igneous extruder](https://teamcofh.com/docs/thermal-expansion/igneous-extruder/). It is a machine that mixes hot and cold fluids to create items, (Mainly stone, cobblestone or sandstone).

### So...
Would it be possible to also have it make your stone / cobblestone / sandstone also generate in it?

**Comment by bookerthegeek** [comment]
https://github.com/CoFH/Feedback/issues/1406

Issue added on COFH. They said they would be taking care of it. :)

**Comment by Aang23** [comment]
Thanks ! That's better if done on there side.
