### ISSUE TITLE
Breaking Particles Missing

### ISSUE THREAD

**Issue by DarkYuan** [Aang23/UndergroundBiomesConstructs#41]
**Version Tested:** 1.3.1 (Jan 4)
UBified Mossy Cobble (and probably others) are missing a breaking particle. It currently displays the magenta checker tile.

**Comment by DarkYuan** [comment]
Didn't seem to work - here's a picture from the latest update
![2019-01-18_16 47 15](https://user-images.githubusercontent.com/3029695/51412125-f263e280-1b40-11e9-86f3-b3f3985e6874.png)

**Comment by Aang23** [comment]
I just tried once again, and it worked...
Did you build that from github ?
![2019-01-18_21 53 55](https://user-images.githubusercontent.com/23421917/51412405-c6118b80-1b6b-11e9-832d-b9b589467836.png)
![2019-01-18_21 54 02](https://user-images.githubusercontent.com/23421917/51412408-c873e580-1b6b-11e9-917e-797bdc1b00e6.png)

**Comment by DarkYuan** [comment]
Oops, sorry! I derped. I could've sworn I saw there was an update on CurseForge! Thanks for the quick reply.

**Comment by Aang23** [comment]
No problems !

**Comment by CREEATION** [comment]
Also missing for `Komatiite Cobblestone Wall` and `Komatiite Brick Wall`.

![2019-03-17_07 59 14](https://user-images.githubusercontent.com/3277769/54486761-000dbe00-488d-11e9-864c-ae7981b2f60e.png)
![2019-03-17_07 59 15](https://user-images.githubusercontent.com/3277769/54486760-fa17dd00-488c-11e9-9444-501a782698d7.png)
