### ISSUE TITLE
Correct dimensions syntax

### ISSUE THREAD

**Issue by kellixon** [Aang23/UndergroundBiomesConstructs#42]
I want the cobblestone replaced only in dimensions 0 and -6 (aroma:mining biome). How to write in the config?
`S:IncludedDimensions=0,-6` or..?

**Comment by Aang23** [comment]
So there may be a bug. I'm gonna look into it.

**Comment by kellixon** [comment]
With the Cavern mod everything works fine. I confirm that some mods are not supported at this stage.
`S:IncludedDimensions=0,-50,-51,-52,-53,-54,-55,-56,-57,-58,-59`
