### ISSUE TITLE
[Request] Support for partially transparent overlays (alpha blending)

### ISSUE THREAD

**Issue by HariboTer** [Aang23/UndergroundBiomesConstructs#47]
If I'm not mistaken, right now the overlay alpha is interpreted as a binary all-or-nothing, where any overlay pixel with alpha = 0 is discarded and anything with alpha > 0 just fully overrides the RGB of the original texture.
For most vanilla-style ores this is perfectly fine, but there are a few mod or texture pack ore textures for which an overlay texture could imo greatly benefit from alpha blending for visually smoother integration onto the original texture.

**Comment by Aang23** [comment]
Could you name a mod / ressourcepack that does that ?

**Comment by HariboTer** [comment]
An example would be the (overworld) ores from Thaumcraft for which I enabled UBifying for Amber and Quartz ore and was a bit surprised about the missing alpha blending.
<details> 
  <summary>The overlay textures with partial transparency</summary>

  ![ore_amber](https://user-images.githubusercontent.com/3805624/52109619-6781ee00-25fe-11e9-8748-dc73bf86d320.png)

![ore_quartz](https://user-images.githubusercontent.com/3805624/52109620-6781ee00-25fe-11e9-8d82-d259630744df.png)

</details>
I've cut out the non-opaque parts for now, but would be very happy about putting them back in :-)

**Comment by HariboTer** [comment]
Sorry for the possibly stupid question, but I'm just wondering from looking at the commit, are you sure you meant to close this issue and not a quark-related one?

**Comment by Aang23** [comment]
Uh... Yes. Sorry.

**Comment by Aang23** [comment]
Just tried and alpha blending is working.
By the way I added Thaumcraft support natively now.

**Comment by HariboTer** [comment]
If you mean that it already works in the current version on curseforge, then I have to respectfully disagree. I found out that the texture blending behaves differently when OptiFine is installed, but without OptiFine I don't think it works as intended either.

I wrote a program to generate me the partially transparent overlay textures by comparing the ore texture to the default stone texture. If pixels were equal, the overlay pixel was full transparent of course. If the ore texture wasn't a shade of grey, it was taken directly. If it was grey, then I used the alpha blending formula to calculate how transparent the full color white or black would have to be made so that if the original stone texture was blended with it, you'd get the corresponding pixel from the ore texture.

<details> 
  <summary>Here are the resulting textures, which had the exact intended result when tested by overlaying in paint.net: </summary>
   
![ore_amber](https://user-images.githubusercontent.com/3805624/53299136-f61d1000-3836-11e9-9863-b40821a627be.png)
![ore_cinnabar](https://user-images.githubusercontent.com/3805624/53299137-f6b5a680-3836-11e9-951e-e7fdde77b47b.png)
![ore_quartz](https://user-images.githubusercontent.com/3805624/53299138-f6b5a680-3836-11e9-8f78-fd7fa0200d98.png)


</details>

Now the interesting thing is, the alpha blending works perfectly fine for the item block in the inventory.
When you actually place the block however, you get different results, depending on whether OptiFine is installed or not.


<details> 
  <summary>Without OptiFine, the partially transparent pixels are completely ignored. </summary>
   
![2019-02-24_13 12 21](https://user-images.githubusercontent.com/3805624/53299171-5613b680-3837-11e9-8437-2761a28093d3.png)


</details>


<details> 
  <summary>With OptiFine, the result is as described in the OP (but yes, my mistake, I should have mentioned that) - the partially transparent pixels become opaque and the result rather grotesque. </summary>
   
![2019-02-24_13 08 52](https://user-images.githubusercontent.com/3805624/53299192-7cd1ed00-3837-11e9-8f83-f7e2d8496d2a.png)

</details>

Both cases could use a closer look, I think^^

If I misunderstood you and you did indeed fix that in a commit that is just not linked here, then please excuse my digressing.

**Comment by Aang23** [comment]
I did not make any changes in the recent commits to fix that, I simply tested using a texture with alpha blending, made in Gimp.
Further testing's gonna be done. Could you upload those textures here ? So that I can try using those ?

**Comment by HariboTer** [comment]
Of course, there you go :-)
[thaumcraft.zip](https://github.com/Aang23/UndergroundBiomesConstructs/files/2897886/thaumcraft.zip)

**Comment by Aang23** [comment]
I just got it working in my dev envirronement !
Just a question, do you mind if I use your textures instead of those I had made myself ?

**Comment by HariboTer** [comment]
Not at all, I'm happy to contribute :D

**Comment by Aang23** [comment]
This will be in 1.3.2.

**Comment by Aang23** [comment]
Now those will need to be specified as alpha overlays...
