### ISSUE TITLE
Mossy Cobblestone

### ISSUE THREAD

**Issue by NickelHub** [Aang23/UndergroundBiomesConstructs#5]
There are still some bugs with mossy cobblestone. You could also add recipes like the vanilla recipe.
![2018-09-29_18 11 26](https://user-images.githubusercontent.com/26455012/46247976-6dc74a00-c413-11e8-8721-70003f61ed19.png)
![2018-09-29_18 11 29](https://user-images.githubusercontent.com/26455012/46247977-6dc74a00-c413-11e8-9097-9d8f6e712886.png)

**Comment by Aang23** [comment]
Thanks ! Fixed in 1.2.8

**Comment by Aang23** [comment]
Reopened for the crafting part. I had totally forgeten that, will be added soon.

**Comment by Aang23** [comment]
And thanks for testing / reporting so often !

**Comment by NickelHub** [comment]
No problem. I love this mod. :D
