### ISSUE TITLE
Poor Metals and Dense Metals support

### ISSUE THREAD

**Issue by Trinsdar** [Aang23/UndergroundBiomesConstructs#57]
Would it be possible to add support for my mod poor metals and for dense metals?
Only problem is dense metals doesn't have a license, so you'll have to ask permission to use its textures.
Repos are here:
https://github.com/MinecraftModDevelopmentMods/DenseMetals
https://github.com/Trinsdar/Poor-Metals

Edit: I just finished retexturing poor metals overworld textures to have a transparent background,, so therefore you can use those if you want, or you could even just reference the textures from my path instead.

**Comment by Aang23** [comment]
I'm still waiting for DenseMetals to answer... Support for that mod should be in 1.3.3.

**Comment by Trinsdar** [comment]
Well if you can't get an answer in a reasonable amount of time the mod author is on the mmd discord.

**Comment by Trinsdar** [comment]
As for thorium I've tried an alpha overlay and I haven't gotten it to work. It may be possible but it would probably require special code, which means you would also have to add special support for it, and it doesn't seem worth the work.

**Comment by Aang23** [comment]
Alpha support was added recently, but not yet pushed on curseforge. The modification required to make that work only was the rendering layer from BlockRenderLayer.CUTOUT_MIPPED to BlockRenderLayer.TRANSLUCENT.
You should be able to try that out using those builds : http://www.altillimity.com/jenkins/job/Underground%20Biomes/
I'm on the MMD discord too, so I'll ask him there.
