### ISSUE TITLE
Some stones don't drop moss varient

### ISSUE THREAD

**Issue by IronPiston** [Aang23/UndergroundBiomesConstructs#58]
I noticed only Limestone, Siltstone, Chalk, Shale, Dolomite, Chert, and Greywache (Lignite drops as an item) drop their mossy varients, while all the other stone types drop cobblestone. Is this by design, because vanilla mossy stone will drop itself?

**Comment by Aang23** [comment]
No, that's just an error on my side... All mossy stones should drop themselves.
