### ISSUE TITLE
Rendering bug when holding ores

### ISSUE THREAD

**Issue by IronPiston** [Aang23/UndergroundBiomesConstructs#59]
Holding any ore block in 3rd person view(Using F5), causes the block to render behind other blocks, and appear to be missing sides. This doesn't happen with other blocks from UBC, nor in 1st person mode.
![2019-03-02_16 10 38](https://user-images.githubusercontent.com/11603684/53688203-ece3e580-3d05-11e9-810b-a274db895e32.png)
![2019-03-02_16 10 53](https://user-images.githubusercontent.com/11603684/53688204-ece3e580-3d05-11e9-80ad-543d7f43911c.png)

**Comment by Aang23** [comment]
That's surely a sideeffect of the fact those are now translucent blocks...

**Comment by Aang23** [comment]
Just tried on my side, nothing... Are you using Optifine ?

**Comment by IronPiston** [comment]
That's what I thought too, but I just tested with just UBC 1.3.2 and Forge 14.23.5.2815 and got the rendering issue.

**Comment by Aang23** [comment]
Related to https://github.com/Aang23/UndergroundBiomesConstructs/issues/47 and also affects shaders

**Comment by CREEATION** [comment]
This might also be the reason why ores don't work with [Custom Selection Box](https://github.com/shedaniel/CustomSelectionBox-New/issues/3#issuecomment-473622204).

**Comment by Aang23** [comment]
@CREEATION The last commit fixed that.
