### ISSUE TITLE
Metallurgy Phosphorite not working

### ISSUE THREAD

**Issue by al132mc** [Aang23/UndergroundBiomesConstructs#61]
I just updated the mod to v1.3.2, and Metallurgy support was added, which is great, but it seems that Phosphorite ore isn't working

[Screenshot](https://imgur.com/pfZbIDY)
(Note: that in the screenshot it looks like Blue Schist phosphorite genned correctly on the right, but that is actually Infuscolium. They have very similar textures)

**Comment by Aang23** [comment]
Just forgot to add it. My bad.
