### ISSUE TITLE
Add Support for ubified GTCE ores, and make 32*32 textures as in 1.7.10

### ISSUE THREAD

**Issue by MrProton657** [Aang23/UndergroundBiomesConstructs#65]
Add Support for ubified GTCE ores, and make 32*32 textures as in 1.7.10

**Comment by Aang23** [comment]
Where are those 32x32 texture from ? I could ship this as a separate resourcepack project, but htye won't get default in the mod.

**Comment by MrProton657** [comment]
They are from the 1.7.10 version. (check out here: https://minecraft.curseforge.com/projects/undergroundbiomesconstructs )

**Comment by Aang23** [comment]
I need to ask permission for Zeno before using those... I will, but don't expect a quick answer.

**Comment by Aang23** [comment]
Closing this for now. Another issue is already opened about GTCE, and I'm waiting for Zeno to answer...
