### ISSUE TITLE
Geolosys ores don't generate properly

### ISSUE THREAD

**Issue by ZapikCZ** [Aang23/UndergroundBiomesConstructs#66]
Using UndergroundBiomes and Geolosys, ores are correctly replaced by their UB variants, except for the chunks with samples above ground.

![2019-03-09](https://user-images.githubusercontent.com/4521407/54077230-f812b480-42b5-11e9-8846-747c8b1b0a8b.png)

The ores are cut off at the chunk that has samples generated. Other chunks with the vein work fine.

**Comment by Aang23** [comment]
The generation bug should most surely get fixed on Geolosys' side.
I'm gonna take a look at those un-ubfied ores.

**Comment by oitsjustjose** [comment]
So I have a few ideas as to what this might be.

Geolosys has a safeguard where if a block is going to be generated in a chunk that isn't loaded, it's *not* generated but instead saved to WorldData to be generated when the chunk gets loaded. I wonder if what's happening is that UB doesn't do this, decorates the chunk regardless and then when Geolosys goes to generate it sees blocks that it isn't permitted to replace.

Samples generate in the chunk chosen to put ores in - so if the deposit itself spills over into an un-created the safeguard catches it, but the sample placement is **restricted** to the chunk that is known to be created.

@ZapikCZ can you add all of the UB stone blocks to the Geolosys config entry `Blocks mineral deposits can replace` and see if this still happens?

**Comment by McLenwe** [comment]
@oitsjustjose I tried it and did my first tests. Adding the UB Stones to the Geolosys config seem to fix the problem.

**Comment by Aang23** [comment]
I tried, and it does. So I'm closing this issue.
