### ISSUE TITLE
Support for Roulette Ores Mod

### ISSUE THREAD

**Issue by WenXin20** [Aang23/UndergroundBiomesConstructs#68]
[Roulette Ores](https://minecraft.curseforge.com/projects/roulette-ores)
This mod has random events happen whenever the ore is broken, as well as a chance of an event happening with modded ores.
Currently, if I added the ore manually, nothing happens when it's broken. The texture of the ore also uses two separate animated overlay textures, but the json fill only displays one of the textures.
![2019-03-18_12 06 50](https://user-images.githubusercontent.com/12000593/54569843-51f83600-49aa-11e9-9bb3-1fac8a333657.png)

**Comment by Aang23** [comment]
Report this issues to them, the compatibility issue comes from their way of firing their code.
