### ISSUE TITLE
Rendering Issue (1.3.2 Alpha Blending)

### ISSUE THREAD

**Issue by TwilightPSN** [Aang23/UndergroundBiomesConstructs#70]
There seems to be some sort of rendering issue with the ores when generated in the world. When looking at any generated version of an UBC ore with more overlays turned on, you can see caverns and other dark places that are in the direction you are facing when looking at the ore. This does not happen with the ore model from the mods they come from. Another issue is when mining the ores it also renders weirdly and allows you to sort of see what is in front of the ore you are mining.

**Comment by Aang23** [comment]
That's known issue introduced in 1.3.2... Thanks for reporting!

**Comment by Aang23** [comment]
Same as https://github.com/Aang23/UndergroundBiomesConstructs/issues/59
