### ISSUE TITLE
Can you please add support for galacticraft, Ice and fire and ebwizardy if possible

### ISSUE THREAD

**Issue by stefanovich123** [Aang23/UndergroundBiomesConstructs#77]
I simply want galacticraft ores for:
Aluminium
Copper
Silicon
Tin
and ice and fire's:
silver
sapphire
and lastly electroblobs wizardrys crystal ore.

**Comment by Aang23** [comment]
Yes ! No problems.

**Comment by stefanovich123** [comment]
Thank you!

**Comment by Aang23** [comment]
Just a question, did you try following this guide ? 
https://github.com/Aang23/UndergroundBiomesConstructs/wiki/Adding-Ores-from-other-Mods

**Comment by Aang23** [comment]
Closing until getting an answer. It is highly recommended for user to add support themselves through this json system.

**Comment by stefanovich123** [comment]
Sorry for not answering you I thought the conversation is done after you answered me first time.
But to be honest, I removed this mod from my own private modpack because I thought your mod was unnecessary for my modpack.
