### ISSUE TITLE
Breaking block rendering glitch

### ISSUE THREAD

**Issue by TimeConqueror** [Aang23/UndergroundBiomesConstructs#78]
So... When I try to break the block, the breaking process glitches. (It becomes transparent)
![image](https://user-images.githubusercontent.com/25156941/55639508-35456600-57d2-11e9-928d-b82cb4acdc6f.png)

**Comment by Aang23** [comment]
Already fixed in dev.

**Comment by Dimentive** [comment]
@Aang23 Thanks for the fix! 💙

Do you have an estimate on when this version will come out? Or is there a place where people can download these early versions?

**Comment by Aang23** [comment]
No exact estimation since I still have many things I want to do.
But, yes, there is ! It's on the README : http://www.altillimity.com/jenkins/job/Underground%20Biomes/
Download the jar without -sources it the name.

Those are built each time I commit to this repo.

**Comment by Dimentive** [comment]
Awesome! Is this early build stable?

I love the mod, by the way! This is easily one of my favourite biome mods.

**Comment by Aang23** [comment]
Those build are mostly stable, and should not cause any world corruption, etc. But they may contain unfinished features.
