### ISSUE TITLE
[Request] Mining levels

### ISSUE THREAD

**Issue by ghost** [Aang23/UndergroundBiomesConstructs#8]
This is not a big deal, but currently I am trying to overwrite the mining levels for rocks and ores with the mod [Tool Progression](https://minecraft.curseforge.com/projects/tool-progression). I set Sedimentary stones to 1 (Stone tools), Igneous to 2 (Iron) and Metamorphic to 3 (Diamond) which works fine.
However, I'd also like to change this for all the ores. So instead of needing iron tools to mine diamonds, I would need iron tools to mine ores in igneous rocks. This does not seem to work. I am guessing your mod registers the mining level of ores after Tool Progression does, so it overwrites it?
Again, if this is too much work or you don't think it fits the mod, feel free to discard. I can live with it ;-)

**Comment by Aang23** [comment]
What block identifier did you use for the ores? (Just to make sure)

**Comment by Ash70** [comment]
These:
    S:"undergroundbiomes:sedimentary_stone_coal_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_diamond_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_emerald_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_gold_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_immersiveengineering_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_immersiveengineering_ore_1:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_immersiveengineering_ore_2:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_immersiveengineering_ore_3:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_immersiveengineering_ore_4:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_immersiveengineering_ore_5:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_immersiveengineering_ore_5:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_iron_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_lapis_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_redstone_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_tile.gem_ore.amber_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_tile.gem_ore.malachite_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_tile.gem_ore.peridot_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_tile.gem_ore.ruby_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_tile.gem_ore.sapphire_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_tile.gem_ore.tanzanite_ore:*"=pickaxe=1
    S:"undergroundbiomes:sedimentary_stone_tile.gem_ore.topaz_ore:*"=pickaxe=1

    S:"undergroundbiomes:igneous_stone_coal_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_diamond_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_emerald_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_gold_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_immersiveengineering_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_immersiveengineering_ore_1:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_immersiveengineering_ore_2:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_immersiveengineering_ore_3:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_immersiveengineering_ore_4:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_immersiveengineering_ore_5:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_immersiveengineering_ore_5:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_iron_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_lapis_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_redstone_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_tile.gem_ore.amber_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_tile.gem_ore.malachite_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_tile.gem_ore.peridot_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_tile.gem_ore.ruby_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_tile.gem_ore.sapphire_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_tile.gem_ore.tanzanite_ore:*"=pickaxe=2
    S:"undergroundbiomes:igneous_stone_tile.gem_ore.topaz_ore:*"=pickaxe=2

    S:"undergroundbiomes:metamorphic_stone_coal_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_diamond_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_emerald_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_gold_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_immersiveengineering_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_immersiveengineering_ore_1:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_immersiveengineering_ore_2:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_immersiveengineering_ore_3:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_immersiveengineering_ore_4:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_immersiveengineering_ore_5:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_immersiveengineering_ore_5:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_iron_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_lapis_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_redstone_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_tile.gem_ore.amber_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_tile.gem_ore.malachite_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_tile.gem_ore.peridot_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_tile.gem_ore.ruby_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_tile.gem_ore.sapphire_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_tile.gem_ore.tanzanite_ore:*"=pickaxe=3
    S:"undergroundbiomes:metamorphic_stone_tile.gem_ore.topaz_ore:*"=pickaxe=3

**Comment by Aang23** [comment]
There is a bug I have just fixed that may have helped. Here's a BETA build (for testing only) for you to test : http://altillimity.ddns.net/UndergroundBiomesConstructs-1.12-1.3.0.jar

**Comment by Ash70** [comment]
That was quick. Won't be able to test until thursday though.

**Comment by Aang23** [comment]
I think this is related to https://github.com/Aang23/UndergroundBiomesConstructs/issues/6

**Comment by Ash70** [comment]
I managed to do a quick test, it doesn't work. All ores (regardless of stone-type) have the same mining level as the original.
So, sedimentary, igneous and metamorphic coal e.g. all have the same level as vanilla coal ore.

**Comment by Aang23** [comment]
Just to be sure, what happen if you change the level of the vanilla ore and not the UBC ore. (Just to check something)
If this is what I think this is fixable, just a little more complex.

**Comment by Ash70** [comment]
Sorry for the late response, I had some problems with my internet connection.
If I change the level of the vanilla ore, all UBC ores of the same type change into that level.

**Comment by Aang23** [comment]
Great. I know what happens. I am going to be forced to add a config option to allow this to work, but, this is getting fixed soon !

**Comment by Aang23** [comment]
Fixed but I need t wait for the official ToolProgression API...

**Comment by Aang23** [comment]
This is now fixed but you have to use my fork for this to currently work, as the API isn't out yet.

**Comment by Ash70** [comment]
np. Thank you.

**Comment by Aang23** [comment]
You're welcome.
Here's a build of my temporary ToolProgression fork for testing if you want. https://github.com/Aang23/ToolProgression/releases/download/1.12.2/toolprogression-1.12.2-1.5.6.jar
You will also need to change some configs in UBC for this to work.

**Comment by Ash70** [comment]
Did some quick testing and it seems to work, I'll do more intensive testing this week and let you know. However, perhaps it would be best to mark version 1.3.0 as alpha since it crashes with the official tool-progression ([log](https://pastebin.com/RLXnm29s)).

**Comment by Aang23** [comment]
I'm gonna do that, but this is normal...

**Comment by Aang23** [comment]
https://github.com/tyra314/ToolProgression/pull/47
Fixed, but will need a rework if the API changes. As said in the PR, the compatibility is only fixed starting with the official version 1.5.7

**Comment by EvertX** [comment]
I had a problem with my previous account so had to make a new one. I am the OP, thanks so much for this.
