### ISSUE TITLE
Issues with UndergroundBiomes in other dimensions

### ISSUE THREAD

**Issue by jinkhya** [Aang23/UndergroundBiomesConstructs#83]
Hello,

(it's Jin from Discord)
So I finally figured it out \o/

2 issues rose :
- if you use the * in IncludedDimensions so that it uses the ExcludedDimensions, it doesn't seem to apply to other dimensions like deep dark even though excluded only has nether and the end.
  To force it you have to specify dimension IDs in IncludedDimensions.
- Which leads to the second issue. My first point will work just fine on a brand new world. However it doesn't work if you change undergroundBiome config and only delete the dimension folder to reset it. This is because of the file in world/worldSpecificConfig/undergroundbiomes.cfg
That file doesn't update with the new config. 
So if you delete the dimension folder and that file so that it regenerates with the new config, all is good. :)

Hopefully that whole investigation will help you ^^
Jin

**Comment by TwilightPSN** [comment]
So did this actually work for you I can even get the dimension to use the generation in a new world as well as deleting that folder

**Comment by jinkhya** [comment]
It worked for me in deep dark yes. I did try my trick with just a pack with underground biome and the Beneath and it didn't work so it looks like it's not compatible (yet) with that mod :(

**Comment by Aang23** [comment]
Usually when a modded dimension does not work it's beaucause the mod (which adds that dimension), handles it in an unusual way. UBC should be compatible with almost anything.

**Comment by NickelHub** [comment]
It works in the Hunting Dimension. Deep Dark use a very other way of generating. If you have a map installed you can see any Biome in the Deep Dark although there is only Deep Dark generating. For more information about that it is recommended to see source of EU2.

**Comment by Aang23** [comment]
Closing this for now, if this is still an issue, I'll reopen.
