### ISSUE TITLE
Gravel variants are not in the ore dictionary

### ISSUE THREAD

**Issue by Darkiceflame** [Aang23/UndergroundBiomesConstructs#89]
Then new gravel variants do not appear to be included in the gravel oredict entry, meaning they can't be used in recipes such as the Tinker's Construct Grout recipes.

**Comment by Aang23** [comment]
They are but TIC doesn't use oredict for gravel in their recipe. Report this issue to them.

**Comment by Aang23** [comment]
I'll close this.
