### ISSUE TITLE
Gregtech Community Edition Compatability

### ISSUE THREAD

**Issue by bookerthegeek** [Aang23/UndergroundBiomesConstructs#92]
# Heyo! # 
How are you doing today? Anyways I was attempting to make the Gregtech ores compatible with Underground Biomes. I came up with [this](https://gist.github.com/bookerthegeek/e1c71ad746e948f465835ed22c425f25) (it's a work in progress as I need to double check all the oredict to make sure they all got transferred over correctly), which in fact does creates all the GT ores in the UBC stone variants in JEI. It also _very rarely_ causes one of the GT ores in game to spawn as the UBC variant. (As in a single ore block in the vein of ores that spawn. Maybe one ore in a thousand. And not in every vein either)

Also yes, I did go and read both the issue [HERE](https://github.com/Aang23/UndergroundBiomesConstructs/issues/21) and over on the [GTCE ](https://github.com/GregTechCE/GregTech/issues/334) issue tracker.

So the issue is not;
1. The UBC configs are wrong, as the ores do show up in JEI
2. The GTCE configs need tweaking, as their is nothing in the ore generation configs that specify what the ores spawn in.
3. Some base level incompatibility, as the UBC ores do sometimes sorta kinda spawn in game.

So the only thing I can think of is that their is some sort of issue as to when the magic is happening during ore generation. Sadly as I don't know Java from a hole in the ground I am no help in looking into that.

### Versions ###
- Minecraft 1.12.2
- forge-1.12.2-14.23.5.2836-universal.jar
- UndergroundBiomesConstructs-1.12-1.3.3
- gregtech-1.12.2-1.8.0.398

**Comment by Aang23** [comment]
There's an issue in GregTech but the authors won't fix it... So your best bet is using an external ore generation mod such as CoFH World.

**Comment by bookerthegeek** [comment]
That is saddening. I would use an external ore generator but I have yet to find one that is able to be configured to spawning the ores as GT does. 

Just for personal knowledge, what exactly is the error that is causing this to happen?

**Comment by Aang23** [comment]
To keep it simple GTCE has a broken ore spawning system which is far from being standard... Thus it tries to spawn ores in non-existing vanilla stone.
They said there was a config option to force them, but I personally couldn't find it.

**Comment by Aang23** [comment]
Closing this I can't fix that for now.
