### ISSUE TITLE
Gravel and Sand dont work for concrete

### ISSUE THREAD

**Issue by BishopXavierHoffman** [Aang23/UndergroundBiomesConstructs#93]
I'm sure it's headache to code but the gravel and sand added by this mod need to be useable as ingredients for making cement powder. This wouldn't be such a big problem if the gravel and sand in this mod didn't replace all gravel and sand that generates in the vanilla world.

**Comment by Aang23** [comment]
No worries, that's an easy fix, using an automatted json generator...

**Comment by BishopXavierHoffman** [comment]
Cool, sounds good
