### ISSUE TITLE
Gravels and Sands Sound Wrong

### ISSUE THREAD

**Issue by KenyMylankca** [Aang23/UndergroundBiomesConstructs#94]
on block broken or placement, they sound like solid blocks, not sand or gravels. just change the sound type in the main type of block class. easy fix..

**Comment by Stargentian** [comment]
This is a known issue. See #85

**Comment by KenyMylankca** [comment]
21 days, really? such an easy-fix bug and 21 days? wow.

**Comment by Aang23** [comment]
Sorry... I'm working on the 1.13.2 port a lot.
A 1.12.2 bugfix update is planned soon.
