### ISSUE TITLE
[1.12.2] Falling animation totally broken

### ISSUE THREAD

**Issue by NickelHub** [Aang23/UndergroundBiomesConstructs#99]
The animation of falling gravel and sand is totally broken. Sometimes it is a door, a fence, another block or something else. Seems to be both effected gravel and sand.

**Comment by Aang23** [comment]
Could you show me ? I don't have any issues on my side.
And, what's your entire modpack ?

**Comment by NickelHub** [comment]
[modlist.txt](https://github.com/Aang23/UndergroundBiomesConstructs/files/3178130/modlist.txt)

I will provide screenshots later.

**Comment by NickelHub** [comment]
![2019-05-15_00 10 40](https://user-images.githubusercontent.com/26455012/57735760-07dbba00-76a6-11e9-8505-e2508da35113.png)
![2019-05-15_00 10 44](https://user-images.githubusercontent.com/26455012/57735763-09a57d80-76a6-11e9-8dec-4fe52d61410e.png)

**Comment by Aang23** [comment]
That's a very odd issue... I'm more than sure I didn't notice it while using UBC myself. I'm gonna test to be sure this isn't UBC's fault, but I bet this is caused by some other mod.

**Comment by Aang23** [comment]
Well, I tried, and that's definitely caused by another mod. Try removing some of them (Optifine? Even if I don't think that's the cause), to see if this fixes it.

**Comment by NickelHub** [comment]
It is not Optifine. I removed it. The gravel turned into flowers as I placed them above grass.

**Comment by cosmicdan** [comment]
> It is not Optifine. I removed it. The gravel turned into flowers as I placed them above grass.

Remove more and test, and repeat until you find the mod that causes the problem.

**Comment by Aang23** [comment]
This is not an UBC bug for sure. Please do what @cosmicdan said... Also make sure you're running an up-to-date forge build.

**Comment by Aang23** [comment]
Also, I'm closing this for now. If needed, just ask me and I'll reopen this issue.

**Comment by Aang23** [comment]
A comment on curseforge revealed this only happened when an ID extender coremod was in use... I'll take a look at this again.

**Comment by NickelHub** [comment]
Yeah, I can confirm. I used JustEnoughIDs. By replacing JustEnoughIDs with NotEnoughIDs, the bug has disappeared.

**Comment by Aang23** [comment]
Since JEID makes deep changes into the game I suspect it's not directly caused by UBC. it works with NEI, so unless there's a true need for JEID compat, I'm closing this for now.

**Comment by floral-qua-floral** [comment]
I've heard NEID can have world corruption problems, and [its mod page](https://www.curseforge.com/minecraft/mc-mods/notenoughids) recommends using JEID instead. If the falling block issue can be fixed from Underground Biomes's end, I feel like JEID support would be really great, since it's just not safe to be using NEID.

[Relevant JEID issue report](https://github.com/DimensionalDevelopment/JustEnoughIDs/issues/46).
